version: "3.7"
services:
  bot:
    build: .
    container_name: freeverse_bot
    environment:
      - DISCORD_BOT_TOKEN
      - DEBUG_MODE
      - REDIS_URL=redis://redis
    image: ikngtty/freeverse
  redis:
    container_name: freeverse_redis
    image: redis:4-alpine
    volumes:
      - freeverse_redis:/data
volumes:
  freeverse_redis:
