name: Run Tests
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run RSpec
        uses: ./.github/actions/run-rspec
